/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TicketType = IDL.Variant({
  'ServiceRequest' : IDL.Null,
  'Incident' : IDL.Null,
});
export const TicketPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'ITAgent' : IDL.Null,
  'Manager' : IDL.Null,
  'MasterAdmin' : IDL.Null,
  'EndUser' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'department' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'department' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'incidentInProgress' : IDL.Nat,
  'serviceRequestInProgress' : IDL.Nat,
  'serviceRequestResolved' : IDL.Nat,
  'incidentClosed' : IDL.Nat,
  'incidentResolved' : IDL.Nat,
  'totalResolved' : IDL.Nat,
  'totalOpen' : IDL.Nat,
  'totalInProgress' : IDL.Nat,
  'serviceRequestClosed' : IDL.Nat,
  'totalClosed' : IDL.Nat,
  'serviceRequestOpen' : IDL.Nat,
  'incidentOpen' : IDL.Nat,
});
export const TicketStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'authorId' : IDL.Principal,
  'createdAt' : Time,
  'text' : IDL.Text,
});
export const Ticket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'title' : IDL.Text,
  'assigneeId' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'reporterId' : IDL.Principal,
  'ticketType' : TicketType,
  'category' : IDL.Text,
  'priority' : TicketPriority,
  'comments' : IDL.Vec(Comment),
});
export const TicketFilter = IDL.Record({
  'status' : IDL.Opt(TicketStatus),
  'assigneeId' : IDL.Opt(IDL.Principal),
  'ticketType' : IDL.Opt(TicketType),
  'priority' : IDL.Opt(TicketPriority),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignTicket' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createTicket' : IDL.Func(
      [TicketType, IDL.Text, IDL.Text, IDL.Text, TicketPriority],
      [IDL.Nat],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getTicket' : IDL.Func([IDL.Nat], [Ticket], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTickets' : IDL.Func([TicketFilter], [IDL.Vec(Ticket)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TicketType = IDL.Variant({
    'ServiceRequest' : IDL.Null,
    'Incident' : IDL.Null,
  });
  const TicketPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'ITAgent' : IDL.Null,
    'Manager' : IDL.Null,
    'MasterAdmin' : IDL.Null,
    'EndUser' : IDL.Null,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'department' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'department' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'incidentInProgress' : IDL.Nat,
    'serviceRequestInProgress' : IDL.Nat,
    'serviceRequestResolved' : IDL.Nat,
    'incidentClosed' : IDL.Nat,
    'incidentResolved' : IDL.Nat,
    'totalResolved' : IDL.Nat,
    'totalOpen' : IDL.Nat,
    'totalInProgress' : IDL.Nat,
    'serviceRequestClosed' : IDL.Nat,
    'totalClosed' : IDL.Nat,
    'serviceRequestOpen' : IDL.Nat,
    'incidentOpen' : IDL.Nat,
  });
  const TicketStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'authorId' : IDL.Principal,
    'createdAt' : Time,
    'text' : IDL.Text,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'title' : IDL.Text,
    'assigneeId' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'reporterId' : IDL.Principal,
    'ticketType' : TicketType,
    'category' : IDL.Text,
    'priority' : TicketPriority,
    'comments' : IDL.Vec(Comment),
  });
  const TicketFilter = IDL.Record({
    'status' : IDL.Opt(TicketStatus),
    'assigneeId' : IDL.Opt(IDL.Principal),
    'ticketType' : IDL.Opt(TicketType),
    'priority' : IDL.Opt(TicketPriority),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignTicket' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createTicket' : IDL.Func(
        [TicketType, IDL.Text, IDL.Text, IDL.Text, TicketPriority],
        [IDL.Nat],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getTicket' : IDL.Func([IDL.Nat], [Ticket], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTickets' : IDL.Func([TicketFilter], [IDL.Vec(Ticket)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };