/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'authorId' : Principal,
  'createdAt' : Time,
  'text' : string,
}
export interface DashboardStats {
  'incidentInProgress' : bigint,
  'serviceRequestInProgress' : bigint,
  'serviceRequestResolved' : bigint,
  'incidentClosed' : bigint,
  'incidentResolved' : bigint,
  'totalResolved' : bigint,
  'totalOpen' : bigint,
  'totalInProgress' : bigint,
  'serviceRequestClosed' : bigint,
  'totalClosed' : bigint,
  'serviceRequestOpen' : bigint,
  'incidentOpen' : bigint,
}
export interface Ticket {
  'id' : bigint,
  'status' : TicketStatus,
  'title' : string,
  'assigneeId' : [] | [Principal],
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'reporterId' : Principal,
  'ticketType' : TicketType,
  'category' : string,
  'priority' : TicketPriority,
  'comments' : Array<Comment>,
}
export interface TicketFilter {
  'status' : [] | [TicketStatus],
  'assigneeId' : [] | [Principal],
  'ticketType' : [] | [TicketType],
  'priority' : [] | [TicketPriority],
}
export type TicketPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type TicketStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export type TicketType = { 'ServiceRequest' : null } |
  { 'Incident' : null };
export type Time = bigint;
export interface User {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'department' : string,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'department' : string,
}
export type UserRole = { 'ITAgent' : null } |
  { 'Manager' : null } |
  { 'MasterAdmin' : null } |
  { 'EndUser' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignTicket' : ActorMethod<[bigint, Principal], undefined>,
  'createTicket' : ActorMethod<
    [TicketType, string, string, string, TicketPriority],
    bigint
  >,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getTicket' : ActorMethod<[bigint], Ticket>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTickets' : ActorMethod<[TicketFilter], Array<Ticket>>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTicketStatus' : ActorMethod<[bigint, TicketStatus], undefined>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];