/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Comment {
    id: bigint;
    authorId: Principal;
    createdAt: Time;
    text: string;
}
export interface User {
    principal: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    department: string;
}
export interface Ticket {
    id: bigint;
    status: TicketStatus;
    title: string;
    assigneeId?: Principal;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    reporterId: Principal;
    ticketType: TicketType;
    category: string;
    priority: TicketPriority;
    comments: Array<Comment>;
}
export interface TicketFilter {
    status?: TicketStatus;
    assigneeId?: Principal;
    ticketType?: TicketType;
    priority?: TicketPriority;
}
export interface DashboardStats {
    incidentInProgress: bigint;
    serviceRequestInProgress: bigint;
    serviceRequestResolved: bigint;
    incidentClosed: bigint;
    incidentResolved: bigint;
    totalResolved: bigint;
    totalOpen: bigint;
    totalInProgress: bigint;
    serviceRequestClosed: bigint;
    totalClosed: bigint;
    serviceRequestOpen: bigint;
    incidentOpen: bigint;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
    role: UserRole;
    department: string;
}
export enum TicketPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export enum TicketStatus {
    Open = "Open",
    Closed = "Closed",
    InProgress = "InProgress",
    Resolved = "Resolved"
}
export enum TicketType {
    ServiceRequest = "ServiceRequest",
    Incident = "Incident"
}
export enum UserRole {
    ITAgent = "ITAgent",
    Manager = "Manager",
    MasterAdmin = "MasterAdmin",
    EndUser = "EndUser"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(ticketId: bigint, text: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignTicket(id: bigint, assigneeId: Principal): Promise<void>;
    createTicket(ticketType: TicketType, title: string, description: string, category: string, priority: TicketPriority): Promise<bigint>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDashboardStats(): Promise<DashboardStats>;
    getMyProfile(): Promise<User | null>;
    getTicket(id: bigint): Promise<Ticket>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listTickets(filter: TicketFilter): Promise<Array<Ticket>>;
    registerUser(name: string, department: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTicketStatus(id: bigint, status: TicketStatus): Promise<void>;
    updateUserRole(userPrincipal: Principal, newRole: UserRole): Promise<void>;
}
import type { Comment as _Comment, Ticket as _Ticket, TicketFilter as _TicketFilter, TicketPriority as _TicketPriority, TicketStatus as _TicketStatus, TicketType as _TicketType, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTicket(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTicket(arg0, arg1);
            return result;
        }
    }
    async createTicket(arg0: TicketType, arg1: string, arg2: string, arg3: string, arg4: TicketPriority): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTicket(to_candid_TicketType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_TicketPriority_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTicket(to_candid_TicketType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_TicketPriority_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicket(arg0: bigint): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicket(arg0);
                return from_candid_Ticket_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicket(arg0);
            return from_candid_Ticket_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTickets(arg0: TicketFilter): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTickets(to_candid_TicketFilter_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTickets(to_candid_TicketFilter_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTicketStatus(arg0: bigint, arg1: TicketStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketStatus(arg0, to_candid_TicketStatus_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketStatus(arg0, to_candid_TicketStatus_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_TicketPriority_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketPriority): TicketPriority {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TicketType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketType): TicketType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_User_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Time;
    role: _UserRole;
    department: string;
}): {
    name: string;
    createdAt: Time;
    role: UserRole;
    department: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n10(_uploadFile, _downloadFile, value.role),
        department: value.department
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TicketStatus;
    title: string;
    assigneeId: [] | [Principal];
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    reporterId: Principal;
    ticketType: _TicketType;
    category: string;
    priority: _TicketPriority;
    comments: Array<_Comment>;
}): {
    id: bigint;
    status: TicketStatus;
    title: string;
    assigneeId?: Principal;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    reporterId: Principal;
    ticketType: TicketType;
    category: string;
    priority: TicketPriority;
    comments: Array<Comment>;
} {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assigneeId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.assigneeId)),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        reporterId: value.reporterId,
        ticketType: from_candid_TicketType_n23(_uploadFile, _downloadFile, value.ticketType),
        category: value.category,
        priority: from_candid_TicketPriority_n25(_uploadFile, _downloadFile, value.priority),
        comments: value.comments
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    department: string;
}): {
    principal: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    department: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n10(_uploadFile, _downloadFile, value.role),
        department: value.department
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ITAgent: null;
} | {
    Manager: null;
} | {
    MasterAdmin: null;
} | {
    EndUser: null;
}): UserRole {
    return "ITAgent" in value ? UserRole.ITAgent : "Manager" in value ? UserRole.Manager : "MasterAdmin" in value ? UserRole.MasterAdmin : "EndUser" in value ? UserRole.EndUser : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
}): TicketStatus {
    return "Open" in value ? TicketStatus.Open : "Closed" in value ? TicketStatus.Closed : "InProgress" in value ? TicketStatus.InProgress : "Resolved" in value ? TicketStatus.Resolved : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ServiceRequest: null;
} | {
    Incident: null;
}): TicketType {
    return "ServiceRequest" in value ? TicketType.ServiceRequest : "Incident" in value ? TicketType.Incident : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): TicketPriority {
    return "Low" in value ? TicketPriority.Low : "High" in value ? TicketPriority.High : "Medium" in value ? TicketPriority.Medium : "Critical" in value ? TicketPriority.Critical : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n8(_uploadFile, _downloadFile, x));
}
function to_candid_TicketFilter_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketFilter): _TicketFilter {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_TicketPriority_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketPriority): _TicketPriority {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_TicketType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): _TicketType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: TicketStatus;
    assigneeId?: Principal;
    ticketType?: TicketType;
    priority?: TicketPriority;
}): {
    status: [] | [_TicketStatus];
    assigneeId: [] | [Principal];
    ticketType: [] | [_TicketType];
    priority: [] | [_TicketPriority];
} {
    return {
        status: value.status ? candid_some(to_candid_TicketStatus_n29(_uploadFile, _downloadFile, value.status)) : candid_none(),
        assigneeId: value.assigneeId ? candid_some(value.assigneeId) : candid_none(),
        ticketType: value.ticketType ? candid_some(to_candid_TicketType_n3(_uploadFile, _downloadFile, value.ticketType)) : candid_none(),
        priority: value.priority ? candid_some(to_candid_TicketPriority_n5(_uploadFile, _downloadFile, value.priority)) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Time;
    role: UserRole;
    department: string;
}): {
    name: string;
    createdAt: _Time;
    role: _UserRole;
    department: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n34(_uploadFile, _downloadFile, value.role),
        department: value.department
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    Open: null;
} | {
    Closed: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
} {
    return value == TicketStatus.Open ? {
        Open: null
    } : value == TicketStatus.Closed ? {
        Closed: null
    } : value == TicketStatus.InProgress ? {
        InProgress: null
    } : value == TicketStatus.Resolved ? {
        Resolved: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    ITAgent: null;
} | {
    Manager: null;
} | {
    MasterAdmin: null;
} | {
    EndUser: null;
} {
    return value == UserRole.ITAgent ? {
        ITAgent: null
    } : value == UserRole.Manager ? {
        Manager: null
    } : value == UserRole.MasterAdmin ? {
        MasterAdmin: null
    } : value == UserRole.EndUser ? {
        EndUser: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): {
    ServiceRequest: null;
} | {
    Incident: null;
} {
    return value == TicketType.ServiceRequest ? {
        ServiceRequest: null
    } : value == TicketType.Incident ? {
        Incident: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
} {
    return value == TicketPriority.Low ? {
        Low: null
    } : value == TicketPriority.High ? {
        High: null
    } : value == TicketPriority.Medium ? {
        Medium: null
    } : value == TicketPriority.Critical ? {
        Critical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
